# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Github Avtivity Graph

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Download github-graph.svg file
        run: |
          mkdir assets 
          curl -L https://github-readme-activity-graph.vercel.app/graph?username=zhanyeye&height=280&bg_color=fffff0&color=708090&area_color=9e4c98&line=9e4c98&point=24292e -o ./assets/github-graph.svg

      # push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     
